# Generated by Django 5.0.2 on 2024-02-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('catname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('test1', models.TextField()),
                ('o1', models.TextField()),
                ('o2', models.TextField()),
                ('o3', models.TextField()),
                ('o4', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('userid', models.IntegerField()),
                ('corname', models.TextField()),
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('cimg', models.ImageField(upload_to='images/')),
                ('cdes1', models.TextField()),
                ('cdes2', models.TextField()),
                ('cdes3', models.TextField()),
                ('cdate', models.DateField(auto_now_add=True)),
                ('dur', models.TextField()),
                ('author', models.TextField()),
                ('enc', models.IntegerField(default=0)),
                ('crating', models.IntegerField()),
                ('com', models.BooleanField(default=False)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyapp.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Coudata',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vhead', models.TextField()),
                ('vilink', models.TextField()),
                ('vdes1', models.TextField()),
                ('vdes2', models.TextField()),
                ('vdes3', models.TextField()),
                ('vdes4', models.TextField()),
                ('vdes5', models.TextField()),
                ('testid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('com', models.BooleanField(default=False)),
                ('corname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyapp.courses')),
            ],
        ),
    ]
