# Generated by Django 5.0.2 on 2024-02-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyapp', '0003_alter_courses_enc_remove_courses_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coudata',
            name='vilink',
            field=models.URLField(),
        ),
    ]
