# Generated by Django 5.0.2 on 2024-02-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyapp', '0004_alter_coudata_vilink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coudata',
            name='vdes2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coudata',
            name='vdes3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coudata',
            name='vdes4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coudata',
            name='vilink',
            field=models.URLField(max_length=300),
        ),
    ]
